name: fantastic-lamp
channels:
- conda-forge
- bioconda
- anaconda
- defaults
dependencies:
  - vg==1.45.0
  - odgi==0.6.2
  - minimap2==2.22
  - seqwish==0.7.2
  - pandas==1.4.2
  - pv==1.6.6
  - libjemalloc==5.2.1
  - pytest==7.2.0
