name: fantastic-lamp
channels:
- conda-forge
- bioconda
- anaconda
- defaults
dependencies:
  - vg==1.45
  - odgi==0.6.2
  - minimap2==2.22
  - seqwish==0.7.2
  - pandas
  - pv
  - libjemalloc==5.2.1
  - pytest
