name: fantastic-lamp
channels:
- defaults
- anaconda
- bioconda
- conda-forge


dependencies:
  - glibc==2.17
  - vg
  - odgi
  - minimap2
  - seqwish
  - pandas
  - pv
  - libjemalloc==5.2.1
  - pytest
