name: simple-test

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master ]

jobs:
  run-script:
    runs-on: ubuntu-20.04
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Add conda to system path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH
          
      
      - name: Restore conda cache
        uses: actions/cache@v3
        with:
          path: $CONDA/pkgs
          key: Linux-conda-${{ hashFiles('**/environment.yaml') }}
          restore-keys: |
            Linux-conda-${{ hashFiles('**/environment.yaml') }}
        env:
          CONDA_CACHE_HIT: 'true'

      - name: Restore conda environment from cache
        uses: actions/cache@v3
        with:
          path: $CONDA/envs/base
          key: ${{ runner.os }}-conda-env-${{ hashFiles('**/environment.yaml') }}
          restore-keys: |
            ubuntu-20.04-conda-env-${{ hashFiles('**/environment.yaml') }}
        env: 
          CONDA_ENV_HIT: 'true'

      
      - name: Install dependencies
        if: ${{ (env.CONDA_CACHE_HIT != 'true') &&
            (env.CONDA_ENV_HIT != 'true') }}
        run: |
          pip install pytest
          conda env update --file environment.yaml --name base --prune
          
      - name: Cache conda packages
        uses: actions/cache@v3
        with:
          path: $CONDA/pkgs
          key: ${{ runner.os }}-conda-${{ hashFiles('**/environment.yaml') }}
          restore-keys: |
            ubuntu-20.04-conda-${{ hashFiles('**/environment.yaml') }}

      - name: Save conda environment to cache
        uses: actions/cache@v3
        with:
          path: $CONDA/envs/base
          key: ${{ runner.os }}-conda-env-${{ hashFiles('**/environment.yaml') }}



      - name: cd
        run: cd Test
        shell: bash

      - uses: actions/checkout@v3
      - name: test script
        run: |
          nice bash find_coverage_test.sh
        shell: bash
        working-directory: Test
        
        
