name: simple-test

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master ]

jobs:
  run-script:
    runs-on: ubuntu-20.04
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Add conda to system path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH
          
      
      
      - name: Install dependencies
        if: ${{ (env.CONDA_CACHE_HIT != 'true') &&
            (env.CONDA_ENV_HIT != 'true') }}
        run: |
          conda env update --file environment.yaml --name base --prune



      - name: cd
        run: cd Test
        shell: bash

      - uses: actions/checkout@v3
      - name: test script
        run: |
          nice bash find_coverage.sh -t
        shell: bash
        # working-directory: Test
        
        
